version: "3.1"

networks:
  network-zabbix:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 172.16.60.0/24
      
services:
  postgres-server:
    container_name: postgres-${COMPOSE_PROJECT_NAME}
    image: postgres:13.6
    networks:
      - network-zabbix
    ports:
      - "5432:5432"
    volumes:
      - "./postgres-data:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
      PG_DATA: /var/lib/postgresql/data/pgdata

  zabbix-server:
    container_name: zabbix-server-${COMPOSE_PROJECT_NAME}
    image: zabbix/zabbix-server-pgsql:ubuntu-6.4-latest
    networks:
      network-zabbix:
        ipv4_address: 172.16.60.200
    links:
      - postgres-server
    restart: always
    ports:
      - "10051:10051"
    volumes:
      - "./zabbix/alertscripts:/usr/lib/zabbix/alertscripts"
      - "./zabbix/externalscripts:/usr/lib/zabbix/externalscripts"
      - "./zabbix/config:/etc/zabbix"
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
    depends_on:
      - postgres-server

  zabbix-frontend:
    container_name: zabbix-frontend-${COMPOSE_PROJECT_NAME}
    image: zabbix/zabbix-web-apache-pgsql:ubuntu-6.4-latest
    networks:
      - network-zabbix
    links:
      - postgres-server
    restart: always
    ports:
      - "80:8080"
      - "443:8443"
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: America/Argentina/Buenos_Aires
    depends_on:
      - postgres-server
      - zabbix-server

  grafana:
    container_name: grafana-${COMPOSE_PROJECT_NAME}
    image: grafana/grafana:10.0.3
    networks:
      - network-zabbix
    links:
      - postgres-server
      - zabbix-server
    restart: always
    ports:
      - "3000:3000"
    environment:
      - GF_INSTALL_PLUGINS=alexanderzobnin-zabbix-app
      - GRAFANA_VERSION=latest
    depends_on:
      - postgres-server
      - zabbix-server
  zabbix-agent:
    container_name: zabbix-agent-${COMPOSE_PROJECT_NAME}
    image: zabbix/zabbix-agent:alpine-6.4-latest
    user: root
    networks:
      network-zabbix:
        ipv4_address: 172.16.60.100
    links:
      - zabbix-server
    restart: always
    privileged: true
    volumes:
      - /var/run:/var/run
    ports:
      - "10050:10050"
    environment:
      - ZBX_HOSTNAME=Zabbix server
      - ZBX_SERVER_HOST=172.16.60.200